/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import AboutMe from 'src/components/AboutMe/AboutMe';
import ButtonPrimaryDefault from 'src/components/ButtonPrimaryDefault/ButtonPrimaryDefault';

const Component21 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const AboutMe1 = styled(AboutMe)(({ theme }) => ({
  width: `438.23px`,
  height: `598px`,
  margin: `0px`,
}));

const ButtonPrimaryDefault1 = styled(ButtonPrimaryDefault)(({ theme }) => ({
  width: `182px`,
  height: `71px`,
  position: `absolute`,
  left: `119px`,
  top: `506px`,
}));

function Component2(props) {
  return (
    <Component21 className={props.className}>
      <AboutMe1 />
      <ButtonPrimaryDefault1 />
    </Component21>
  );
}

export default Component2;
