/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Rectangle1Image from 'src/assets/images/Group98_Rectangle_1.png';
import Ellipse1Image from 'src/assets/images/Group98_Ellipse_1.png';
import VectorImage from 'src/assets/images/Group98_Vector.png';
import { styled } from '@mui/material/styles';
import NavigationBar from 'src/components/NavigationBar/NavigationBar';
import ButtonPrimaryDefault from 'src/components/ButtonPrimaryDefault/ButtonPrimaryDefault';

const Group981 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
  width: 'fit-content',
});

const Rectangle1 = styled('img')({
  height: `587px`,
  width: `1438px`,
  objectFit: `cover`,
  margin: `0px`,
});

const ScrollDownToContinue = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `47.17457580566406px`,
  textTransform: `none`,
  height: `47px`,
  width: `280px`,
  position: `absolute`,
  left: `577px`,
  top: `503px`,
});

const Group97 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `32px`,
  width: `32px`,
  left: `701px`,
  top: `546px`,
});

const Ellipse1 = styled('img')({
  height: `32px`,
  width: `32px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Vector = styled('img')({
  height: `14.74px`,
  width: `17.01px`,
  position: `absolute`,
  left: `7px`,
  top: `11px`,
});

const TheCounter70CountrieSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Lato`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const TheCounter70CountrieSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 165, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Lato`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const TheCounter70CountrieSpan3 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Lato`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const TheCounter70CountrieSpan4 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 165, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Lato`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const TheCounter70CountrieSpan5 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Lato`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
});

const TheCounter70Countrie = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Lato`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  height: `44px`,
  width: `595px`,
  position: `absolute`,
  left: `419px`,
  top: `124px`,
});

const LeaveYourMarkOnAllOv = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Lato`,
  fontWeight: `800`,
  fontSize: `64px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `89px`,
  textTransform: `none`,
  height: `179px`,
  width: `1036px`,
  position: `absolute`,
  left: `199px`,
  top: `182px`,
});

const NavigationBar1 = styled(NavigationBar)(({ theme }) => ({
  height: `55.67px`,
  width: `1247px`,
  position: `absolute`,
  left: `73px`,
  top: `17px`,
}));

const ButtonPrimaryDefault1 = styled(ButtonPrimaryDefault)(({ theme }) => ({
  height: `85px`,
  width: `218px`,
  position: `absolute`,
  left: `608px`,
  top: `388px`,
}));

function Group98(props) {
  return (
    <Group981 className={props.className}>
      <Rectangle1 src={Rectangle1Image} loading="lazy" alt={'Rectangle 1'} />
      <ScrollDownToContinue>{`Scroll Down to Continue`}</ScrollDownToContinue>
      <Group97>
        <Ellipse1 src={Ellipse1Image} loading="lazy" alt={'Ellipse 1'} />
        <Vector src={VectorImage} loading="lazy" alt={'Vector'} />
      </Group97>
      <TheCounter70Countrie>
        <TheCounter70CountrieSpan1>{`THE COUNTER: `}</TheCounter70CountrieSpan1>
        <TheCounter70CountrieSpan2>{`70`}</TheCounter70CountrieSpan2>
        <TheCounter70CountrieSpan3>{` Countries    `}</TheCounter70CountrieSpan3>
        <TheCounter70CountrieSpan4>{`1036`}</TheCounter70CountrieSpan4>
        <TheCounter70CountrieSpan5>{` Cities `}</TheCounter70CountrieSpan5>
      </TheCounter70Countrie>
      <LeaveYourMarkOnAllOv>
        {`Leave your mark on all 
over the world  `}
      </LeaveYourMarkOnAllOv>
      <NavigationBar1 />
      <ButtonPrimaryDefault1 />
    </Group981>
  );
}

export default Group98;
