/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const ButtonPrimaryDefault1 = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `85px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle = styled('div')({
  backgroundColor: `rgba(3, 54, 255, 1)`,
  borderRadius: `8px`,
  width: `218px`,
  height: `85px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Primary = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Lato`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `51px`,
  top: `27px`,
});

function ButtonPrimaryDefault(props) {
  return (
    <ButtonPrimaryDefault1 className={props.className}>
      <Rectangle></Rectangle>
      <Primary>{`Read More`}</Primary>
    </ButtonPrimaryDefault1>
  );
}

export default ButtonPrimaryDefault;
